### ISSUE TITLE
Action object has no attribute 'as_dict'

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/noviflow#18]
Hi,

Running the Noviflow Napp with Kytos 2022.2 gives us the following error:

```
Oct 26 17:46:08 8ba74f12c575 kytos.core.helpers:ERROR helpers:130:  listen_to handler: <function Main.on_flow_stats_check_consistency at 0x7f04e8241310>, args: (<Main(flow_manager, stopped 139655919937280)>, KytosEvent('kytos/of_core.flow_stats.received', {'switch': Switch('00:00:00:00:00:00:00:0c'), 'replies_flows': [<napps.kytos.of_core.v0x04.flow.Flow object at 0x7f041446b7c0>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f041446bb50>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f041446b430>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f0414384820>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f04143846a0>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f0414384b20>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7f0414384640>]}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 126, in handler_context,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 144, in on_flow_stats_check_consistency,     self.check_consistency(event.content["switch"]),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 328, in check_consistency,     self.check_alien_flows(switch),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 387, in check_alien_flows,     flows = self.switch_flows_by_id(switch, self.is_not_ignored_flow),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 344, in switch_flows_by_id,     return {flow.id: flow for flow in switch.flows if filter_flow(flow)},   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 344, in <dictcomp>,     return {flow.id: flow for flow in switch.flows if filter_flow(flow)},   File "//var/lib/kytos/napps/../napps/kytos/of_core/flow.py", line 102, in id,     flow_str = self.as_json(sort_keys=True, include_id=False),   File "//var/lib/kytos/napps/../napps/kytos/of_core/flow.py", line 208, in as_json,     return json.dumps(self.as_dict(include_id), sort_keys=sort_keys),   File "//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 350, in as_dict,     flow_dict['instructions'] = [instruction.as_dict() for,   File "//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 350, in <listcomp>,     flow_dict['instructions'] = [instruction.as_dict() for,   File "//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 216, in as_dict,     instruction_dict['actions'] = [action.as_dict(),   File "//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 216, in <listcomp>,     instruction_dict['actions'] = [action.as_dict(), AttributeError: 'NoneType' object has no attribute 'as_dict',
```

Steps to reproduce:

1. Run Kytos docker container `amlight/kytos:2022.2rc1`
2. Install kytos/noviflow `python3 -m pip install -e git+https://github.com/kytos-ng/noviflow@master#egg=kytos-noviflow`
3. Create a flow for testing: `curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H 'Content-type: application/json' -d '{"flows": [{"priority": 10, "match": {"in_port": 23}, "actions": [{"action_type": "push_int"}, {"action_type": "output", "port": 2}]}]}'`

Expected result:

the flow should be created, and the Kytos server should stay stable along successive executions of the consistency check

Actual result:

the flow is installed, but kytos raise exceptions on each consistency check execution.

**Comment by italovalcy** [comment]
Hi @viniarck I've investigated this a little more and it looks like the `kytos/noviflow` Napp is missing the mapping from Python object classes to actual Action class (we only have the mapping from string to Action). The following patch fixes the issue above:

```
diff --git a/main.py b/main.py
index 955e155..8c6dbf7 100644
--- a/main.py
+++ b/main.py
@@ -10,6 +10,13 @@ from napps.amlight.noviflow.of_core.v0x04.action import (
     NoviActionSendReport,
     NoviActionSetBfdData,
 )
+from napps.amlight.noviflow.pyof.v0x04.action import (
+    NoviActionAddIntMetadata as OFNoviActionAddIntMetadata,
+    NoviActionPopInt as OFNoviActionPopInt,
+    NoviActionPushInt as OFNoviActionPushInt,
+    NoviActionSendReport as OFNoviActionSendReport,
+    NoviActionSetBfdData as OFNoviActionSetBfdData,
+)
 from napps.kytos.of_core.v0x04.flow import Action

 from kytos.core import KytosNApp
@@ -20,6 +27,11 @@ NOVIFLOW_ACTIONS = {
     "add_int_metadata": NoviActionAddIntMetadata,
     "pop_int": NoviActionPopInt,
     "send_report": NoviActionSendReport,
+    OFNoviActionSetBfdData: NoviActionSetBfdData,
+    OFNoviActionPushInt: NoviActionPushInt,
+    OFNoviActionAddIntMetadata: NoviActionAddIntMetadata,
+    OFNoviActionPopInt: NoviActionPopInt,
+    OFNoviActionSendReport: NoviActionSendReport,
 }
``` 

A similar approach is done at `kytos/of_core`: https://github.com/kytos-ng/of_core/blob/master/v0x04/flow.py#L182-L191
